services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trekz
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/trekz?schema=public'
    depends_on:
      - postgres
    volumes:
      - .:/app # Mount your entire project directory
      # - /app/node_modules # Use an anonymous volume for node_modules to avoid conflicts
    command: sh -c "pnpm prisma migrate deploy && pnpm start:dev"

volumes:
  postgres_data:
